### PR TITLE
Support DK2 with WebVR and polyfill for Google Cardboard

### PR DESCRIPTION
**Pull request by brianpeiris**
This uses the new WebVR APIs via the helpful library and polyfill provided by [WebVR Boilerplate](https://github.com/borismus/webvr-boilerplate).
This removes the need for RiftServer, WebSockets and vr.js adds support for DK2 via the new WebVR browser builds and Google Cardboard (via Chrome for Android or the ChromeShell WebVR build).
As a side-effect, we lose the ability to see the map and settings dialog in VR and also lose gamepad support for the most part (although this can be added back).

### CODE REVIEW

**Comment by troffmo5** [comment]
Thanks for your work! You integrated it nicely.
Before merging it i'd like to know why you have 2 commits with the same diff? ( d195086 &  8d24884)
I would intergrate the fist 2 commits ("De-linting" & "Use WebVR polyfill")

**Comment by brianpeiris** [comment]
Ah, d195086 also removes the RiftServer zip file. I'll try to squash the commits.

**Comment by brianpeiris** [comment]
Done. Also updated the readme.

**Comment by troffmo5** [comment]
It looks much better. Thanks!

**Pull request merged**
